workspace:
  base: /go
  path: src/github.com/umputun/docker-logger

pipeline:
  
  build:
    image: golang:1.9-alpine
    commands:
      - cd app
      - export CGO_ENABLED=0
      - export GOOS=linux
      - export GOARCH=amd64
      - go build -v ./...

  docker_master:
    image: plugins/docker
    repo: umputun/docker-logger
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
    event: push

  docker_branch:
    image: plugins/docker
    repo: umputun/docker-logger
    secrets: [ docker_username, docker_password ]
    when:
      branch:
        exclude: [ master, release/* ]
    event: push
  