workspace:
  base: /go
  path: src/github.com/umputun/docker-logger

pipeline:
  
  build:
    image: golang:1.9-alpine
    commands:
      - cd app
      - go build -v ./...

  docker:
    image: plugins/docker
    repo: umputun/logger
    secrets: [ docker_username, docker_password ]
    tags: ${DRONE_REPO_BRANCH}
