[[constraint]]
  name = "gopkg.in/natefinch/lumberjack.v2"
  version = "2.1.0"

[[constraint]]
  name = "github.com/fsouza/go-dockerclient"
  version = "1.2.1"

[[override]]
  name = "github.com/docker/docker"
  revision = "a422774e593b33bd287d9890544ad9e09b380d8c"

[prune]
  go-tests = true
  unused-packages = true
